version: "3.8"
services:
  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=oleksii
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
